// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9Mu7DQ18vIhQIp38c4aiQayurn7Cx1k',
    appId: '1:433664923866:web:dbcc3dfaea6e84afacade3',
    messagingSenderId: '433664923866',
    projectId: 'college-pro-82349',
    authDomain: 'college-pro-82349.firebaseapp.com',
    databaseURL: 'https://college-pro-82349-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-pro-82349.appspot.com',
    measurementId: 'G-CDNQNGHEMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDKr0hJ4gjzSR74Ke51b2JDyvRA9HNJx8',
    appId: '1:433664923866:android:6723d30dab964ffaacade3',
    messagingSenderId: '433664923866',
    projectId: 'college-pro-82349',
    databaseURL: 'https://college-pro-82349-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-pro-82349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC54-CugEEuEotvo4TaNwReXu-mxf8Ynbg',
    appId: '1:433664923866:ios:81d25adede82054cacade3',
    messagingSenderId: '433664923866',
    projectId: 'college-pro-82349',
    databaseURL: 'https://college-pro-82349-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-pro-82349.appspot.com',
    iosBundleId: 'com.example.kwikq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC54-CugEEuEotvo4TaNwReXu-mxf8Ynbg',
    appId: '1:433664923866:ios:66cfd7ec50bf0d82acade3',
    messagingSenderId: '433664923866',
    projectId: 'college-pro-82349',
    databaseURL: 'https://college-pro-82349-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-pro-82349.appspot.com',
    iosBundleId: 'com.example.kwikq.RunnerTests',
  );
}
